In [3]:
import requests
from bs4 import BeautifulSoup
import pickle

In [4]:
def url_to_transcript(url):
    page = requests.get(url).text
    
    soup = BeautifulSoup(page, "html")
    text = [p.text for p in soup.find_all("p")]
    print(url)
    return text

In [7]:
urls = ['http://scrapsfromtheloft.com/2017/05/06/louis-ck-oh-my-god-full-transcript/',
        'http://scrapsfromtheloft.com/2017/04/11/dave-chappelle-age-spin-2017-full-transcript/',
        'http://scrapsfromtheloft.com/2018/03/15/ricky-gervais-humanity-transcript/',
        'https://scrapsfromtheloft.com/comedy/jim-gaffigan-comedy-monster-transcript/',
        'http://scrapsfromtheloft.com/2017/05/24/bill-burr-im-sorry-feel-way-2014-full-transcript/',
        'http://scrapsfromtheloft.com/2017/04/21/jim-jefferies-bare-2014-full-transcript/',
        'http://scrapsfromtheloft.com/2017/08/02/john-mulaney-comeback-kid-2015-full-transcript/',
        'https://scrapsfromtheloft.com/comedy/george-carlin-doin-it-again-transcript/',
        'http://scrapsfromtheloft.com/2017/09/19/ali-wong-baby-cobra-2016-full-transcript/',
        'http://scrapsfromtheloft.com/2017/08/03/anthony-jeselnik-thoughts-prayers-2015-full-transcript/',
        'http://scrapsfromtheloft.com/2018/03/03/mike-birbiglia-my-girlfriends-boyfriend-2013-full-transcript/',
        'http://scrapsfromtheloft.com/2017/08/19/joe-rogan-triggered-2016-full-transcript/']

comedians = ['louis', 'dave', 'ricky', 'Jim-G', 'bill', 'Jim-J', 'john', 'George', 'ali', 'anthony', 'mike', 'joe']

In [8]:
transcripts = [url_to_transcript(u) for u in urls]

http://scrapsfromtheloft.com/2017/05/06/louis-ck-oh-my-god-full-transcript/
http://scrapsfromtheloft.com/2017/04/11/dave-chappelle-age-spin-2017-full-transcript/
http://scrapsfromtheloft.com/2018/03/15/ricky-gervais-humanity-transcript/
https://scrapsfromtheloft.com/comedy/jim-gaffigan-comedy-monster-transcript/
http://scrapsfromtheloft.com/2017/05/24/bill-burr-im-sorry-feel-way-2014-full-transcript/
http://scrapsfromtheloft.com/2017/04/21/jim-jefferies-bare-2014-full-transcript/
http://scrapsfromtheloft.com/2017/08/02/john-mulaney-comeback-kid-2015-full-transcript/
https://scrapsfromtheloft.com/comedy/george-carlin-doin-it-again-transcript/
http://scrapsfromtheloft.com/2017/09/19/ali-wong-baby-cobra-2016-full-transcript/
http://scrapsfromtheloft.com/2017/08/03/anthony-jeselnik-thoughts-prayers-2015-full-transcript/
http://scrapsfromtheloft.com/2018/03/03/mike-birbiglia-my-girlfriends-boyfriend-2013-full-transcript/
http://scrapsfromtheloft.com/2017/08/19/joe-rogan-triggered-2016-full-transcript/

In [10]:
def combine_text(list_of_text):
    combined_text = ' '.join(list_of_text)
    return combined_text

In [9]:
data = {comedians[i]: [combine_text(transcripts[i])] for i in range(len(comedians))}

In [11]:
import pandas as pd

df = pd.DataFrame(data).transpose()
df.columns = ['transcript']
df

                                                transcript
louis    Intro\nFade the music out. Let’s roll. Hold th...
dave     This is Dave. He tells dirty jokes for a livin...
ricky    Hello. Hello! How you doing? Great. Thank you....
Jim-G    Thank you! Thank you! Oh, my gosh. Thank you s...
bill     [cheers and applause] All right, thank you! Th...
Jim-J    [Car horn honks] [Audience cheering] [Announce...
john     Armed with boyish charm and a sharp wit, the f...
George   Recorded on January 12–13, 1990, State Theatre...
ali      Ladies and gentlemen, please welcome to the st...
anthony  Thank you. Thank you. Thank you, San Francisco...
mike     Wow. Hey, thank you. Thanks. Thank you, guys. ...
joe      [rock music playing] [audience cheering] [anno...

In [12]:
import re
import string
def clean_data(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

r1 = lambda x: clean_data(x)

In [13]:
df1 = pd.DataFrame(df.transcript.apply(r1))
df1

                                                transcript
louis    intro\nfade the music out let’s roll hold ther...
dave     this is dave he tells dirty jokes for a living...
ricky    hello hello how you doing great thank you wow ...
Jim-G    thank you thank you oh my gosh thank you so mu...
bill      all right thank you thank you very much thank...
Jim-J       ladies and gentlemen please welcome to the ...
john     armed with boyish charm and a sharp wit the fo...
George   recorded on january –  state theatre new bruns...
ali      ladies and gentlemen please welcome to the sta...
anthony  thank you thank you thank you san francisco th...
mike     wow hey thank you thanks thank you guys hey se...
joe         ladies and gentlemen welcome joe rogan  wha...

In [14]:
def clean_data2(text):
  
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)
    return text

r2 = lambda x: clean_data2(x)

In [15]:
# Let's take a look at the updated text
df2 = pd.DataFrame(df1.transcript.apply(r2))
df2

                                                transcript
louis    introfade the music out lets roll hold there l...
dave     this is dave he tells dirty jokes for a living...
ricky    hello hello how you doing great thank you wow ...
Jim-G    thank you thank you oh my gosh thank you so mu...
bill      all right thank you thank you very much thank...
Jim-J       ladies and gentlemen please welcome to the ...
john     armed with boyish charm and a sharp wit the fo...
George   recorded on january –  state theatre new bruns...
ali      ladies and gentlemen please welcome to the sta...
anthony  thank you thank you thank you san francisco th...
mike     wow hey thank you thanks thank you guys hey se...
joe         ladies and gentlemen welcome joe rogan  wha...

In [16]:
import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')
stops = set(stopwords.words('english'))
punctuations = list(string.punctuation)
stops.update(punctuations)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [17]:
def tokenize(text):
    text = word_tokenize(text)
    tf=[]
    for w in text:
      if w not in stops:
        tf.append(w)
    return tf

r3 = lambda x: tokenize(x)

In [18]:
df3 = pd.DataFrame(df2.transcript.apply(r3))
df3

                                                transcript
louis    [introfade, music, lets, roll, hold, lights, l...
dave     [dave, tells, dirty, jokes, living, stare, har...
ricky    [hello, hello, great, thank, wow, calm, shut, ...
Jim-G    [thank, thank, oh, gosh, thank, much, thank, t...
bill     [right, thank, thank, much, thank, thank, than...
Jim-J    [ladies, gentlemen, please, welcome, stage, mr...
john     [armed, boyish, charm, sharp, wit, former, snl...
George   [recorded, january, –, state, theatre, new, br...
ali      [ladies, gentlemen, please, welcome, stage, al...
anthony  [thank, thank, thank, san, francisco, thank, m...
mike     [wow, hey, thank, thanks, thank, guys, hey, se...
joe      [ladies, gentlemen, welcome, joe, rogan, fck, ...

In [19]:
df2.to_pickle('corpus_sneh.pkl')

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english')
data = cv.fit_transform(df2.transcript)
data_dtm = pd.DataFrame(data.toarray(), columns=cv.get_feature_names())
data_dtm.index = df2.index
data_dtm.to_pickle('sneh_dtm.pkl')

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)